dist: bionic
language: csharp
dotnet: "3.1"
mono: none

env:
  global:
    - PATH="$PATH:$HOME/.dotnet/tools"

install:
  - dotnet tool restore 

script:
 - dotnet restore
 - dotnet build --no-restore
 - dotnet test --no-restore
