name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:TreatWarningsAsErrors=true
    - name: Run Tests
      run: dotnet test --no-build

  nupkg:
      name: Generate NuGet Packages
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        name: Install Current .NET SDK
      - name: Generate NuGet Packages
        run: dotnet pack --configuration Release --output nupkg
      - uses: actions/upload-artifact@v2
        if: success() && github.ref == 'refs/heads/main'
        with:
            name: nupkg
            path: nupkg/*
            retention-days: 1
